Repository HomeChefHub/refooding-be, pull requests merged in 2024-07, with the labels that each got.

#2 [chore] swagger springdoc 라이브러리 의존성 추가 #1
  build.gradle
Labels: ⚙️ 설정

#3 [chore] swagger 라이브러리 의존성 추가 수정 #1
  build.gradle
Labels: ⚙️ 설정

#8 [feat] 레시피 관련 엔티티(레시피, 메뉴얼, 재료) 생성 #7
  src/main/java/refooding/api/ApiApplication.java
  src/main/java/refooding/api/domain/common/BaseTimeEntity.java
  src/main/java/refooding/api/domain/recipe/Ingredient.java
  src/main/java/refooding/api/domain/recipe/Manual.java
  src/main/java/refooding/api/domain/recipe/Recipe.java
  src/main/java/refooding/api/domain/recipe/RecipeIngredient.java
  src/main/resources/application-dev.yml
Labels: ✨ 기능

#12 [feat] 식재료 교환, 지역 엔티티 작성
  src/main/java/refooding/api/domain/exchange/Exchange.java
  src/main/java/refooding/api/domain/exchange/ExchangeStatus.java
  src/main/java/refooding/api/domain/exchange/Region.java
Labels: ✨ 기능

#14 Exchange Entity @JoinColumn 수정, common 패키지 루트 이동
  src/main/java/refooding/api/common/domain/BaseTimeEntity.java
  src/main/java/refooding/api/domain/exchange/Exchange.java
  src/main/java/refooding/api/domain/recipe/Ingredient.java
  src/main/java/refooding/api/domain/recipe/Manual.java
  src/main/java/refooding/api/domain/recipe/Recipe.java
  src/main/java/refooding/api/domain/recipe/RecipeIngredient.java
Labels: 🛠️ 리팩토링

#18 [refactor] 식재료 교환 지역 목록 조회 API
  src/main/java/refooding/api/domain/exchange/controller/ExchangeController.java
  src/main/java/refooding/api/domain/exchange/dto/RegionResponse.java
  src/main/java/refooding/api/domain/exchange/entity/Exchange.java
  src/main/java/refooding/api/domain/exchange/entity/ExchangeStatus.java
  src/main/java/refooding/api/domain/exchange/entity/Region.java
  src/main/java/refooding/api/domain/exchange/repository/RegionRepository.java
  src/main/java/refooding/api/domain/exchange/service/RegionService.java
  src/test/java/refooding/api/ApiApplicationTests.java
  src/test/java/refooding/api/domain/exchange/repository/RegionRepositoryTest.java
  src/test/resources/application.yml
  src/test/resources/exchange-data.sql
Labels: ✨ 기능

#19 [chore] swagger 설정
  src/main/java/refooding/api/common/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
Labels: ⚙️ 설정

#22 [feat] 식재료 교환 등록, 수정, 삭제 API 구현
  src/main/java/refooding/api/common/domain/BaseTimeEntity.java
  src/main/java/refooding/api/domain/exchange/controller/ExchangeController.java
  src/main/java/refooding/api/domain/exchange/dto/request/ExchangeCreateRequest.java
  src/main/java/refooding/api/domain/exchange/dto/request/ExchangeUpdateRequest.java
  src/main/java/refooding/api/domain/exchange/dto/response/RegionResponse.java
  src/main/java/refooding/api/domain/exchange/entity/Exchange.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeRepository.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeService.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
  src/main/java/refooding/api/domain/exchange/service/RegionService.java
  src/test/java/refooding/api/domain/exchange/repository/ExchangeRepositoryTest.java
  src/test/java/refooding/api/domain/exchange/repository/RegionRepositoryTest.java
  src/test/java/refooding/api/utils/EntityManagerUtil.java
Labels: ✨ 기능

#24 [feat] 테스트 위한 data.sql 추가
  .gitignore
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeResponse.java
  src/main/java/refooding/api/domain/exchange/entity/Exchange.java
  src/main/resources/exchange-data.sql
Labels: ✨ 기능

#27 [feat] 식재료 교환 상세 조회 API
  src/main/java/refooding/api/domain/exchange/controller/ExchangeController.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeDetailResponse.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeResponse.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeRepository.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeService.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
  src/main/resources/application-local.yml
Labels: ✨ 기능

#29 [feat] Querydsl 설정
  .gitignore
  build.gradle
  src/main/java/refooding/api/common/config/QuerydslConfig.java
Labels: ⚙️ 설정

#30 [refactor] 레시피 조회 API 리팩토링
  src/main/java/refooding/api/domain/recipe/controller/RecipeController.java
  src/main/java/refooding/api/domain/recipe/repository/RecipeRepository.java
  src/main/java/refooding/api/domain/recipe/service/RecipeService.java
Labels: 🛠️ 리팩토링

#35 [hotfix] 레시피 상세 조회시 메뉴얼 순서대로 조회되도록 수정
  src/main/java/refooding/api/domain/recipe/entity/Recipe.java
  src/main/java/refooding/api/domain/recipe/entity/RecipeData.java
  src/main/java/refooding/api/domain/recipe/service/RecipeService.java
  src/main/resources/recipe-data.json
Labels: ✨ 기능

#36 [feat] 식재료 교환 목록 조회 API 구현
  src/main/java/refooding/api/common/qeurydsl/QuerydslRepositoryUtils.java
  src/main/java/refooding/api/domain/exchange/controller/ExchangeController.java
  src/main/java/refooding/api/domain/exchange/controller/ExchangeControllerOpenApi.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeResponse.java
  src/main/java/refooding/api/domain/exchange/dto/response/RegionResponse.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepository.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeRepository.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeSearchCondition.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeService.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
  src/main/java/refooding/api/domain/exchange/service/RegionService.java
  src/main/resources/application-local.yml
  src/main/resources/exchange-data.sql
Labels: ✨ 기능

#40 CustomException, ExceptionCode, GlobalExceptionHandler 추가
  src/main/java/refooding/api/common/exception/CustomException.java
  src/main/java/refooding/api/common/exception/ExceptionCode.java
  src/main/java/refooding/api/common/exception/ExceptionResponse.java
  src/main/java/refooding/api/common/handler/GlobalExceptionHandler.java
Labels: ✨ 기능

#42 API 요청 데이터 검증 validation 라이브러리 추가 및 GlobalExceptionHandler 예외 추가
  build.gradle
  src/main/java/refooding/api/common/exception/FieldErrorResponse.java
  src/main/java/refooding/api/common/handler/GlobalExceptionHandler.java
Labels: ✨ 기능
