Repository HomeChefHub/refooding-be, pull requests merged in 2024-08, with the labels that each got.

#49 [refactor] 식재료 교환 지역명 변경, 식재료 교환 상세조회 응답 회원 정보 추가
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeDetailResponse.java
  src/main/resources/exchange-data.sql
Labels: 🛠️ 리팩토링

#53 채팅 관련 엔티티 추가, 웺소켓 라이브러리 의존성 추가 및 설정, 채팅방 생성, 목록 조회 API, 채팅메시지 생성 API
  build.gradle
  src/main/java/refooding/api/common/config/WebSocketConfig.java
  src/main/java/refooding/api/common/exception/ExceptionCode.java
  src/main/java/refooding/api/domain/chat/controller/MessageController.java
  src/main/java/refooding/api/domain/chat/controller/RoomController.java
  src/main/java/refooding/api/domain/chat/controller/RoomControllerOpenApi.java
  src/main/java/refooding/api/domain/chat/dto/request/MessageRequest.java
  src/main/java/refooding/api/domain/chat/dto/request/RoomCreateRequest.java
  src/main/java/refooding/api/domain/chat/dto/response/MessageResponse.java
  src/main/java/refooding/api/domain/chat/dto/response/RoomResponse.java
  src/main/java/refooding/api/domain/chat/entity/Message.java
  src/main/java/refooding/api/domain/chat/entity/MessageStatus.java
  src/main/java/refooding/api/domain/chat/entity/Room.java
  src/main/java/refooding/api/domain/chat/entity/RoomMember.java
  src/main/java/refooding/api/domain/chat/entity/RoomMemberStatus.java
  src/main/java/refooding/api/domain/chat/repository/MessageCustomRepository.java
  src/main/java/refooding/api/domain/chat/repository/MessageCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/chat/repository/MessageRepository.java
  src/main/java/refooding/api/domain/chat/repository/RoomMemberRepository.java
  src/main/java/refooding/api/domain/chat/repository/RoomRepository.java
  src/main/java/refooding/api/domain/chat/service/MessageService.java
  src/main/java/refooding/api/domain/chat/service/MessageServiceImpl.java
  src/main/java/refooding/api/domain/chat/service/RoomService.java
  src/main/java/refooding/api/domain/chat/service/RoomServiceImpl.java
  src/main/java/refooding/api/domain/exchange/controller/ExchangeController.java
  src/main/java/refooding/api/domain/exchange/dto/request/ExchangeCreateRequest.java
  src/main/java/refooding/api/domain/exchange/dto/request/ExchangeUpdateRequest.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeDetailResponse.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeResponse.java
  src/main/java/refooding/api/domain/exchange/dto/response/RegionResponse.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepositoryImpl.java
Labels: ✨ 기능

#55 [fix] 식재료 목록 조회시 삭제된 데이터 반영하여 조회
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
Labels: 🐛 버그

#57 채팅방 나가기, 채팅 목록 응답에 마지막 메시지 읽음 여부 데이터 추가
  src/main/java/refooding/api/domain/chat/controller/RoomController.java
  src/main/java/refooding/api/domain/chat/controller/RoomControllerOpenApi.java
  src/main/java/refooding/api/domain/chat/dto/response/RoomResponse.java
  src/main/java/refooding/api/domain/chat/entity/Message.java
  src/main/java/refooding/api/domain/chat/entity/MessageStatus.java
  src/main/java/refooding/api/domain/chat/entity/Room.java
  src/main/java/refooding/api/domain/chat/entity/RoomMember.java
  src/main/java/refooding/api/domain/chat/repository/MessageCustomRepository.java
  src/main/java/refooding/api/domain/chat/repository/MessageCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/chat/repository/RoomMemberRepository.java
  src/main/java/refooding/api/domain/chat/repository/RoomRepository.java
  src/main/java/refooding/api/domain/chat/service/MessageServiceImpl.java
  src/main/java/refooding/api/domain/chat/service/RoomService.java
  src/main/java/refooding/api/domain/chat/service/RoomServiceImpl.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepository.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
Labels: 🛠️ 리팩토링, ✨ 기능

#59 [fix] 식재료 교환 update 버그 수정 #58
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
Labels: 🐛 버그

#64 [fix] 냉장고 requestMemberId -> memberId 필드명 변경
  src/main/java/refooding/api/domain/refrigerator/dto/MemberIngredientDeleteRequest.java
  src/main/java/refooding/api/domain/refrigerator/dto/MemberIngredientUpdateRequest.java
  src/main/java/refooding/api/domain/refrigerator/service/MemberIngredientService.java
Labels: 🐛 버그

#66 [feat] AWS S3 이미지 업로드 구현
  .gitignore
  build.gradle
  src/main/java/refooding/api/common/aws/S3Uploader.java
  src/main/java/refooding/api/common/config/AwsConfig.java
  src/main/java/refooding/api/common/exception/ExceptionCode.java
  src/main/java/refooding/api/common/util/ImageUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ 기능

#68 [feat] 식재료 교환 이미지 업로드 구현
  src/main/java/refooding/api/domain/exchange/controller/ExchangeController.java
  src/main/java/refooding/api/domain/exchange/dto/request/ExchangeCreateRequest.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeDetailResponse.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeResponse.java
  src/main/java/refooding/api/domain/exchange/entity/Exchange.java
  src/main/java/refooding/api/domain/exchange/entity/ExchangeImage.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeImageCustomRepository.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeImageCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeImageRepository.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeRepository.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
  src/test/java/refooding/api/domain/exchange/repository/ExchangeRepositoryTest.java
Labels: ✨ 기능

#71 [feat] DB 설정
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🛠️ 리팩토링, ✨ 기능

#73 [refactor] 레시피 커서 기반 검색, 상세조회, 좋아요, 좋아요 목록 조회
  src/main/java/refooding/api/domain/member/controller/MemberController.java
  src/main/java/refooding/api/domain/recipe/controller/RecipeController.java
  src/main/java/refooding/api/domain/recipe/controller/RecipeControllerOpenApi.java
  src/main/java/refooding/api/domain/recipe/dto/FavoriteRecipeToggleResponse.java
  src/main/java/refooding/api/domain/recipe/dto/ManualResponse.java
  src/main/java/refooding/api/domain/recipe/dto/RecipeDetailResponse.java
  src/main/java/refooding/api/domain/recipe/dto/RecipeIngredientResponse.java
  src/main/java/refooding/api/domain/recipe/dto/RecipeResponse.java
  src/main/java/refooding/api/domain/recipe/dto/request/RecipeLikeRequest.java
  src/main/java/refooding/api/domain/recipe/dto/response/ManualResponse.java
  src/main/java/refooding/api/domain/recipe/dto/response/RecipeDetailResponse.java
  src/main/java/refooding/api/domain/recipe/dto/response/RecipeLikeResponse.java
  src/main/java/refooding/api/domain/recipe/dto/response/RecipeResponse.java
  src/main/java/refooding/api/domain/recipe/entity/FavoriteRecipe.java
  src/main/java/refooding/api/domain/recipe/entity/Ingredient.java
  src/main/java/refooding/api/domain/recipe/entity/Manual.java
  src/main/java/refooding/api/domain/recipe/entity/Recipe.java
  src/main/java/refooding/api/domain/recipe/entity/RecipeData.java
  src/main/java/refooding/api/domain/recipe/entity/RecipeLike.java
  src/main/java/refooding/api/domain/recipe/repository/FavoriteRecipeRepository.java
  src/main/java/refooding/api/domain/recipe/repository/IngredientRepository.java
  src/main/java/refooding/api/domain/recipe/repository/RecipeCustomRepository.java
  src/main/java/refooding/api/domain/recipe/repository/RecipeCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/recipe/repository/RecipeIngredientRepository.java
  src/main/java/refooding/api/domain/recipe/repository/RecipeLikeRepository.java
  src/main/java/refooding/api/domain/recipe/repository/RecipeRepository.java
  src/main/java/refooding/api/domain/recipe/service/RecipeService.java
  src/main/java/refooding/api/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/refooding/api/domain/recipe/service/RecipeSetupService.java
  src/main/java/refooding/api/domain/refrigerator/controller/MemberIngredientController.java
  src/main/java/refooding/api/domain/refrigerator/entity/MemberIngredient.java
  src/main/java/refooding/api/domain/refrigerator/repository/MemberIngredientRepository.java
  src/main/java/refooding/api/domain/refrigerator/service/MemberIngredientService.java
  src/main/resources/recipe-data.json
Labels: 🛠️ 리팩토링

#77 식재료 이미지 업로드 사이즈 및 레시피, 식재료 API 수정
  .gitignore
  src/main/java/refooding/api/common/config/SwaggerConfig.java
  src/main/java/refooding/api/domain/recipe/controller/RecipeController.java
  src/main/java/refooding/api/domain/recipe/controller/RecipeControllerOpenApi.java
  src/main/java/refooding/api/domain/recipe/dto/response/ManualResponse.java
  src/main/java/refooding/api/domain/recipe/dto/response/RecipeDetailResponse.java
  src/main/java/refooding/api/domain/recipe/entity/Manual.java
  src/main/resources/application.yml
  src/main/resources/recipe-data.json
Labels: 🐛 버그, ✨ 기능

#78 [refactor] 냉장고 재료 커서 기반 목록 조회, 생성, 수정, 삭제 전체적인 코드 정리 및 수정
  src/main/java/refooding/api/common/aws/S3Uploader.java
  src/main/java/refooding/api/common/exception/ExceptionCode.java
  src/main/java/refooding/api/domain/fridge/controller/IngredientController.java
  src/main/java/refooding/api/domain/fridge/controller/IngredientControllerOpenApi.java
  src/main/java/refooding/api/domain/fridge/dto/request/IngredientCreateRequest.java
  src/main/java/refooding/api/domain/fridge/dto/request/IngredientUpdateRequest.java
  src/main/java/refooding/api/domain/fridge/dto/response/IngredientResponse.java
  src/main/java/refooding/api/domain/fridge/entity/Fridge.java
  src/main/java/refooding/api/domain/fridge/entity/FridgeIngredient.java
  src/main/java/refooding/api/domain/fridge/entity/Ingredient.java
  src/main/java/refooding/api/domain/fridge/entity/IngredientImage.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeIngredientCustomRepository.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeIngredientCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeIngredientRepository.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeIngredientSearchCondition.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeRepository.java
  src/main/java/refooding/api/domain/fridge/repository/IngredientImageCustomRepository.java
  src/main/java/refooding/api/domain/fridge/repository/IngredientImageCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/fridge/repository/IngredientImageRepository.java
  src/main/java/refooding/api/domain/fridge/repository/IngredientRepository.java
  src/main/java/refooding/api/domain/fridge/service/IngredientService.java
  src/main/java/refooding/api/domain/fridge/service/IngredientServiceImpl.java
  src/main/java/refooding/api/domain/recipe/service/RecipeServiceImpl.java
  src/main/java/refooding/api/domain/refrigerator/controller/MemberIngredientController.java
  src/main/java/refooding/api/domain/refrigerator/dto/MemberIngredientCreateRequest.java
  src/main/java/refooding/api/domain/refrigerator/dto/MemberIngredientDeleteRequest.java
  src/main/java/refooding/api/domain/refrigerator/dto/MemberIngredientResponse.java
  src/main/java/refooding/api/domain/refrigerator/dto/MemberIngredientUpdateRequest.java
  src/main/java/refooding/api/domain/refrigerator/entity/MemberIngredient.java
  src/main/java/refooding/api/domain/refrigerator/repository/MemberIngredientRepository.java
  src/main/java/refooding/api/domain/refrigerator/service/MemberIngredientService.java
Labels: 🛠️ 리팩토링

#80 [feat] 레시피 상세조회 응답 데이터 매뉴얼 리스트 정렬 및 seq 데이터 제거
  src/main/java/refooding/api/domain/recipe/dto/response/ManualResponse.java
  src/main/java/refooding/api/domain/recipe/dto/response/RecipeDetailResponse.java
Labels: 🛠️ 리팩토링, ✨ 기능

#82 [fix] 냉장고 재료 조회 API 오류 수정
  src/main/java/refooding/api/domain/fridge/service/IngredientServiceImpl.java
Labels: 🐛 버그

#83 [feat] 식재료 수정 API 이미지 업데이트 구현
  src/main/java/refooding/api/common/exception/ExceptionCode.java
  src/main/java/refooding/api/common/s3/S3Uploader.java
  src/main/java/refooding/api/domain/exchange/controller/ExchangeController.java
  src/main/java/refooding/api/domain/exchange/controller/ExchangeControllerOpenApi.java
  src/main/java/refooding/api/domain/exchange/dto/request/ExchangeCreateRequest.java
  src/main/java/refooding/api/domain/exchange/dto/request/ExchangeUpdateRequest.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeDetailResponse.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeResponse.java
  src/main/java/refooding/api/domain/exchange/entity/Exchange.java
  src/main/java/refooding/api/domain/exchange/entity/ExchangeImage.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeImageRepository.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeRepository.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeService.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
Labels: ✨ 기능

#85 [feat] 냉장고 재료 수정 API 이미지 업데이 구현
  src/main/java/refooding/api/domain/fridge/controller/IngredientController.java
  src/main/java/refooding/api/domain/fridge/dto/request/IngredientCreateRequest.java
  src/main/java/refooding/api/domain/fridge/dto/request/IngredientUpdateRequest.java
  src/main/java/refooding/api/domain/fridge/entity/Fridge.java
  src/main/java/refooding/api/domain/fridge/entity/FridgeIngredient.java
  src/main/java/refooding/api/domain/fridge/entity/IngredientImage.java
  src/main/java/refooding/api/domain/fridge/repository/IngredientImageRepository.java
  src/main/java/refooding/api/domain/fridge/service/IngredientServiceImpl.java
Labels: ✨ 기능

#87 Fix/86
  src/main/java/refooding/api/common/domain/BaseTimeEntity.java
  src/main/java/refooding/api/domain/chat/dto/response/MessageResponse.java
  src/main/java/refooding/api/domain/chat/entity/Message.java
  src/main/java/refooding/api/domain/chat/entity/Room.java
  src/main/java/refooding/api/domain/chat/entity/RoomMember.java
  src/main/java/refooding/api/domain/chat/repository/RoomMemberRepository.java
  src/main/java/refooding/api/domain/chat/repository/RoomRepository.java
  src/main/java/refooding/api/domain/chat/service/MessageServiceImpl.java
  src/main/java/refooding/api/domain/chat/service/RoomServiceImpl.java
  src/main/java/refooding/api/domain/exchange/dto/response/ExchangeDetailResponse.java
  src/main/java/refooding/api/domain/exchange/entity/Exchange.java
  src/main/java/refooding/api/domain/exchange/entity/ExchangeImage.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeImageRepository.java
  src/main/java/refooding/api/domain/exchange/repository/ExchangeRepository.java
  src/main/java/refooding/api/domain/exchange/service/ExchangeServiceImpl.java
  src/main/java/refooding/api/domain/fridge/entity/FridgeIngredient.java
  src/main/java/refooding/api/domain/fridge/entity/IngredientImage.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeIngredientCustomRepositoryImpl.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeIngredientRepository.java
  src/main/java/refooding/api/domain/fridge/repository/FridgeRepository.java
  src/main/java/refooding/api/domain/fridge/repository/IngredientImageRepository.java
  src/main/java/refooding/api/domain/fridge/service/IngredientServiceImpl.java
  src/main/java/refooding/api/domain/member/entity/Member.java
  src/main/java/refooding/api/domain/member/repository/MemberRepository.java
  src/main/java/refooding/api/domain/member/service/MemberService.java
  src/main/java/refooding/api/domain/recipe/entity/RecipeLike.java
  src/main/java/refooding/api/domain/recipe/repository/RecipeLikeRepository.java
  src/main/resources/exchange-data.sql
  src/main/resources/member-data.sql
Labels: 🐛 버그, 🛠️ 리팩토링
